version: "3.9"

services:
  openobserve:
    image: openobserve/openobserve:latest
    container_name: openobserve
    environment:
      ZO_ROOT_USER_EMAIL: "root@gmail.com"
      ZO_ROOT_USER_PASSWORD: "admin"
    ports:
      - "5080:5080"
    volumes:
      - openobserve-data:/data
    restart: always
    networks:
      - otel-network

  flask-app:
    build: .
    container_name: flask-app
    ports:
      - "5011:5011"
    networks:
      - otel-network
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://openobserve:5080/api/default/v1/traces
      - OTEL_EXPORTER_OTLP_AUTH=Basic cm9vdEBleGFtcGxlLmNvbTpDb21wbGV4cGFzcyMxMjM=

networks:
  otel-network:
    driver: bridge

volumes:
  openobserve-data:
