
services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - otel-net

  openobserve:
    image: openobserve/openobserve:latest
    container_name: openobserve
    environment:
      ZO_ROOT_USER_EMAIL: "root@gmail.com"
      ZO_ROOT_USER_PASSWORD: "admin"
      ZO_AUTH_ENABLED: "false"
    ports:
      - "5080:5080"
    volumes:
      - openobserve-data:/data
    networks:
      - otel-net

  threats-app:
    build: ./app
    container_name: threats-app
    ports:
      - "5020:5020"
    env_file:
      - .env
    networks:
      - otel-net
    depends_on:
      - mongo
      - fetcher-app

  fetcher-app:
    build: ./fetcher
    container_name: fetcher-app
    env_file:
      - .env
    networks:
      - otel-net
    depends_on:
      - mongo

volumes:
  mongo-data:
  openobserve-data:

networks:
  otel-net:
    driver: bridge