
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcher-app
  namespace: threat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fetcher-app
  template:
    metadata:
      labels:
        app: fetcher-app
    spec:
      containers:
        - name: fetcher-app
          image: dockerelvis/fetcher-app:293d6b7
          envFrom:
            - configMapRef:
                name: fetcher-config
            - secretRef:
                name: fetcher-secret
