
apiVersion: v1
kind: Secret
metadata:
  name: threats-secret
  namespace: threat
type: Opaque
data:
  OTEL_EXPORTER_OTLP_AUTH: QmFzaWMgY203dmREQm5nYldscGJtTjBaR1Z1WlhKM2FYcGxYMmhsYzNSbGNtVnVaR1Z1YVc1bQ==
  VT_API_KEY: YjBmYTdkNmRkZTY4Mzk4N2ZlMjljODQxZDRmMTdiNjVlMDIzOGRhODIwYzBjNWIzOTIwOTA1MGQwODM4NDUwYw==  # Replace with actual base64
  OTX_API_KEY: NmExZWRiMTgzMmVjNTI0M2JmOTJjYjk5MzJiM2UxMzcxZTk0ZDA0NmY1YjViMTA4YWY4MmRiYmNlZWZkNjk3MA==   # Replace with actual base64
# echo -n 'value' | base64
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: threats-config
  namespace: threat
data:
  MONGODB_URI: mongodb://mongo:27017/
  MONGODB_DB: threatintel
  MONGODB_COLLECTION: threats
  OTEL_EXPORTER_OTLP_ENDPOINT: http://openobserve:5080/api/default/v1/traces
  OTEL_EXPORTER_OTLP_METRIC_ENDPOINT: http://openobserve:5080/api/default/v1/metrics
  OTEL_EXPORTER_OTLP_LOGS_ENDPOINT: http://openobserve:5080/api/default/v1/logs
  OTEL_STREAM_NAME: Openobserve-stream
  ALIENVAULT_URL: https://otx.alienvault.com/api/v1/pulses/subscribed
  SERVICE_NAME_UI: Threats-UI
  SERVICE_NAME_FETCHER: Threats-Fetcher

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetcher-app
  namespace: threat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fetcher-app
  template:
    metadata:
      labels:
        app: fetcher-app
    spec:
      containers:
        - name: fetcher-app
          image: dockerelvis/fetcher-app:293d6b7
          envFrom:
            - configMapRef:
                name: threats-config
            - secretRef:
                name: threats-secret
