# k8s/threats-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: threats-app
  namespace: threat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: threats-app
  template:
    metadata:
      labels:
        app: threats-app
    spec:
      containers:
        - name: threats-app
          image: dockerelvis/threats-app:293d6b7
          ports:
            - containerPort: 5020
          envFrom:
            - configMapRef:
                name: threats-config
---
apiVersion: v1
kind: Service
metadata:
  name: threats-app
  namespace: threat
spec:
  selector:
    app: threats-app
  ports:
    - port: 5020
      targetPort: 5020
